version: 2.1
workflows:
  testing:
    jobs:
      - runner-test
jobs:
  runner-test:
    machine: true
    resource_class: promeg/linux
    steps:
      - checkout
      - run: echo "Hi I'm on Runners!"
      - run: ls
      - run: ./gradlew test